# Generated by Django 5.1.3 on 2024-11-27 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_todo_assigned_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='assigned_to',
        ),
    ]
